sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
  - "7"
  - "6"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libasound2-dev
test:
  - npm run test && npm run codecov