sudo: required
dist: trusty
language: node_js
cache:
  directories:
    - node_modules
node_js:
  - 10
  - 9
  - 8.9.0
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libasound2-dev
test:
  - npm run test
after_success:
  - npm run codecov
